### ISSUE TITLE
Masih Work gak sir?

### ISSUE THREAD

**Issue by 0zunu** [trisnawan/AndroTools#1]

**Comment by trisnawan** [comment]
Masih ges, ini sering gw update dan dipake buat projekan-projekan gw

**Comment by 0zunu** [comment]
> Masih ges, ini sering gw update dan dipake buat projekan-projekan gw

project perusahaan lu bukan nih, takutnya gw udh ngulik ngulik di hak milik :v

**Comment by trisnawan** [comment]
Bukan, ini tools pribadi, hehe. Kalo projek perusahaan gw private

**Comment by 0zunu** [comment]
> Bukan, ini tools pribadi, hehe. Kalo projek perusahaan gw private

wokelah
